import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     <div class="container">
  <div class="main">
    <div class="infoContainer">
      <div class="devInfo">
        <div class="hello">Hello I am,</div>
        <div class="name">Priyanshu Jalan</div>
        <div class="about">Web developer, Web Desiner </div>
        <div>
        <div class="buttons">
          <button class="btn"><i class="fa fa-download"></i> Download CV</button>
          <button class="btn">Contact Me</button>
          </div>
        </div>
      </div>
    </div>
  </div><br>
  <div class="card">
       <img class="respImg" loading="lazy" src="https://codewithharry.nyc3.cdn.digitaloceanspaces.com/assets/62f60049963012281edcc77dd2ec031b.png">
      <span class="cardTitle">Go to About Page</span><br>
    <button class="btn-sm">Read More</button>
  </div>
  <div class="card my-1">
       <img class="respImg" loading="lazy" src="https://codewithharry.nyc3.cdn.digitaloceanspaces.com/assets/62f60049963012281edcc77dd2ec031b.png">
      <span class="cardTitle">Go to Blog Page</span><br>
    <button class="btn-sm">Read More</button>
  </div>
  <div class="card my-1">
       <img class="respImg" loading="lazy" src="https://codewithharry.nyc3.cdn.digitaloceanspaces.com/assets/62f60049963012281edcc77dd2ec031b.png">
      <span class="cardTitle">My Projects Page</span><br>
    <button class="btn-sm">Read More</button>
  </div>
  <div class="card my-1">
       <img class="respImg" loading="lazy" src="https://codewithharry.nyc3.cdn.digitaloceanspaces.com/assets/62f60049963012281edcc77dd2ec031b.png">
      <span class="cardTitle">Go to Contact Page</span><br>
    <button class="btn-sm">Read More</button>
  </div>
  
<footer class="footer">
      <p>Copyright &copy; ProgrammingWithHero.com | 2023</p>
</footer>
    </div>
  )
}
